spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # gmail USERNAME
    password: ${MAIL_PASSWORD} #
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000 # sending mail timeout
          starttls:
            enable: true # some stmp services require TLS.